### ISSUE TITLE
Wrong GPS coordinates are shown on standart telemetry screen

### ISSUE THREAD

**Issue by Linktuner** [wolkstein/MavLink_FrSkySPort#1]
While using converter based on arduino nano 328p with no functional change in code of teensy there are wrong coordinates on the standard telemetry screen. So it has no chanсe to use it for the flown away model search.
![2015-01-11 19 23 36](https://cloud.githubusercontent.com/assets/10487460/5695919/fcfe5426-99c8-11e4-9ccc-c237810e0260.jpg)
it sould be like about 56.312283, 38.146166

**Comment by Davestru** [comment]
We found a bug in the code.
First, you need to do:
(int32_t)(ap_latitude / 100 \* 6);
then compare it to zero, and after multiplied by a hexadecimal number.
We made a patched version for yourself with the correct GPS.
![qa1egmgo-7a](https://cloud.githubusercontent.com/assets/10170802/5704090/05a8fda4-9a7f-11e4-8b47-66bf5f2f2be3.jpg)
Please correct your code and check the radar, you faster and easier to do it in your own code. We are waiting for the updated version! And thanks for the idea!

**Comment by wolkstein** [comment]
thx for pointing out. i never compare this coordinates with real coordinates because the radar works relative to home position. so i will have a look on it.

edit:
which opentx revision did you use?

**Comment by wolkstein** [comment]
i do some tests today and can not confirm this bug. at my taranis, lat & long are shown correctly 
env:
Taranis with opentx 2.0.15
x8r receiver
teensy 3.1 with resistor network to measure lipo cells.
apm 2.6 

this bug need more data.

@Linktuner, you use an arduino nano. this repository contains arduino firmware code to compile and run at an teensy3.1. it is not possible to compile this code for an nano without rewriting at minimum the serial setup.

@Davestru, against which version of GCS_MAVLink did you compile the code. did you use an teensy3.x? and which version of opentx didyou use.

**Comment by wolkstein** [comment]
fixed in https://github.com/wolkstein/MavLink_FrSkySPort/tree/s-c-l-v-rc/MavLink_FrSkySPort_Teensy2_and_ProMini folder.
see
6b3988367931f52359385530baec6e517caf331a
and
6213e7d40a5dc92b2415cf7f254699f609627fd8
/g
wolke

**Comment by FPVCambodia** [comment]
Hi Wolke,

Tks again for your help (on DIY Drones), here is my small bird alive with
your help and readme tutorial on GitHub. I now need to calibrate the Lua
scripts after a few packs as you suggest... and I should be good with a
redundant info on my Taranis.. This small Trifecta Tricopter bird, features
a GPS, osd, Mavlink 3DR, Mavlink to FrSky ( ;) ) and low KV motors with a
4000mAh 3S battery set for 10 to 12 minutes flight...

Here are a few pictures for your reassurance that the community goes to the
end making it working and helpful supporting us forward! Thanks again to
you and Rolph! Well done guys and Tks Again!

https://plus.google.com/+FPVcambodia/posts/M9Abt32Htvq

Kind Regards

On Sat, Mar 28, 2015 at 5:24 PM, wolke notifications@github.com wrote:

> fixed in
> https://github.com/wolkstein/MavLink_FrSkySPort/tree/s-c-l-v-rc/MavLink_FrSkySPort_Teensy2_and_ProMini
> folder.
> see
> 6b39883
> https://github.com/wolkstein/MavLink_FrSkySPort/commit/6b3988367931f52359385530baec6e517caf331a
> and
> 6213e7d
> https://github.com/wolkstein/MavLink_FrSkySPort/commit/6213e7d40a5dc92b2415cf7f254699f609627fd8
> /g
> wolke
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wolkstein/MavLink_FrSkySPort/issues/1#issuecomment-87201954
> .

## 

_Cheers, Enjoy and Safe Flying Lads!_
_www.youtube.com/FPVcambodia_ http://www.youtube.com/FPV_cambodia
_www.google.com/+FPVcambodia http://www.google.com/+FPVcambodia_
