### ISSUE TITLE
Voltage is not showing correctly

### ISSUE THREAD

**Issue by juanej** [wolkstein/MavLink_FrSkySPort#2]
I just started using this script, was using the original one before and everything was working but now I can't get the voltage to show the correct value. In the telemetry page where it shows every cell they're all changing from 0 to 1 values, everything else seems to be working just fine.

I'm using the last taranis version
![2015-01-20 21 30 15](https://cloud.githubusercontent.com/assets/2244029/5830239/c3d3d4ee-a0eb-11e4-85f9-b54810c7b0db.jpg)

**Comment by wolkstein** [comment]
if teensy A0-Ax is not in use (lipo single cell voltage), comment line 87 & 88 in MavLink_FrSkySPort.ino to disable the "Single Cell Lipo Voltage Monitor" functionality to use reported Mavlink voltage instead.

 i add a small notice in README.md. see 7b45586dd2c8db8422854dd35017ec38b8f2f779
